assets:
  overrides: 
    /app: src/main/resources/app

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
    
mongo:
  host: localhost
  port: 27017
  db: palsac